//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExternalBankingRESTService.OnlineBankingSecServRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginInfo", Namespace="http://schemas.datacontract.org/2004/07/ExternalBankingSecurityLibrary")]
    [System.SerializableAttribute()]
    public partial class LoginInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> AdditionalDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ForUnlockingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OTPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExternalBankingRESTService.OnlineBankingSecServRef.PlatformType PlatformTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> AdditionalDetails {
            get {
                return this.AdditionalDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalDetailsField, value) != true)) {
                    this.AdditionalDetailsField = value;
                    this.RaisePropertyChanged("AdditionalDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ForUnlocking {
            get {
                return this.ForUnlockingField;
            }
            set {
                if ((this.ForUnlockingField.Equals(value) != true)) {
                    this.ForUnlockingField = value;
                    this.RaisePropertyChanged("ForUnlocking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IpAddress {
            get {
                return this.IpAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IpAddressField, value) != true)) {
                    this.IpAddressField = value;
                    this.RaisePropertyChanged("IpAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OTP {
            get {
                return this.OTPField;
            }
            set {
                if ((object.ReferenceEquals(this.OTPField, value) != true)) {
                    this.OTPField = value;
                    this.RaisePropertyChanged("OTP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExternalBankingRESTService.OnlineBankingSecServRef.PlatformType PlatformType {
            get {
                return this.PlatformTypeField;
            }
            set {
                if ((this.PlatformTypeField.Equals(value) != true)) {
                    this.PlatformTypeField = value;
                    this.RaisePropertyChanged("PlatformType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenId {
            get {
                return this.TokenIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenIdField, value) != true)) {
                    this.TokenIdField = value;
                    this.RaisePropertyChanged("TokenId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlatformType", Namespace="http://schemas.datacontract.org/2004/07/ExternalBankingSecurityLibrary")]
    public enum PlatformType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnlineBanking = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MobileBanking = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExternalUser", Namespace="http://schemas.datacontract.org/2004/07/ExternalBankingSecurityLibrary")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExternalBankingRESTService.OnlineBankingSecServRef.OnlineBankingUser))]
    public partial class ExternalUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BranchCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChangeRequirementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameEngField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PermissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BranchCode {
            get {
                return this.BranchCodeField;
            }
            set {
                if ((this.BranchCodeField.Equals(value) != true)) {
                    this.BranchCodeField = value;
                    this.RaisePropertyChanged("BranchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChangeRequirement {
            get {
                return this.ChangeRequirementField;
            }
            set {
                if ((this.ChangeRequirementField.Equals(value) != true)) {
                    this.ChangeRequirementField = value;
                    this.RaisePropertyChanged("ChangeRequirement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerNumber {
            get {
                return this.CustomerNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNumberField, value) != true)) {
                    this.CustomerNumberField = value;
                    this.RaisePropertyChanged("CustomerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullNameEng {
            get {
                return this.FullNameEngField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameEngField, value) != true)) {
                    this.FullNameEngField = value;
                    this.RaisePropertyChanged("FullNameEng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Permission {
            get {
                return this.PermissionField;
            }
            set {
                if ((this.PermissionField.Equals(value) != true)) {
                    this.PermissionField = value;
                    this.RaisePropertyChanged("Permission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionID {
            get {
                return this.SessionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIDField, value) != true)) {
                    this.SessionIDField = value;
                    this.RaisePropertyChanged("SessionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnlineBankingUser", Namespace="http://schemas.datacontract.org/2004/07/ExternalBankingSecurityLibrary")]
    [System.SerializableAttribute()]
    public partial class OnlineBankingUser : ExternalBankingRESTService.OnlineBankingSecServRef.ExternalUser {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AllowDataEntryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ApprovementSchemeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExternalBankingRESTService.OnlineBankingSecServRef.LoginResult AuthorizationResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DailyTransactionsLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoodLogonsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLastConfirmerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LimitedAccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double OneTransactionLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExternalBankingRESTService.OnlineBankingSecServRef.ChangePasswordResult PasswordChangeResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecondConfirmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeOfClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ExternalBankingRESTService.OnlineBankingSecServRef.UserGroup> UserGroupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExternalBankingRESTService.OnlineBankingSecServRef.UserSecurityInfo UserSecurityInformationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AllowDataEntry {
            get {
                return this.AllowDataEntryField;
            }
            set {
                if ((this.AllowDataEntryField.Equals(value) != true)) {
                    this.AllowDataEntryField = value;
                    this.RaisePropertyChanged("AllowDataEntry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApprovementScheme {
            get {
                return this.ApprovementSchemeField;
            }
            set {
                if ((this.ApprovementSchemeField.Equals(value) != true)) {
                    this.ApprovementSchemeField = value;
                    this.RaisePropertyChanged("ApprovementScheme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExternalBankingRESTService.OnlineBankingSecServRef.LoginResult AuthorizationResult {
            get {
                return this.AuthorizationResultField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorizationResultField, value) != true)) {
                    this.AuthorizationResultField = value;
                    this.RaisePropertyChanged("AuthorizationResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DailyTransactionsLimit {
            get {
                return this.DailyTransactionsLimitField;
            }
            set {
                if ((this.DailyTransactionsLimitField.Equals(value) != true)) {
                    this.DailyTransactionsLimitField = value;
                    this.RaisePropertyChanged("DailyTransactionsLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GoodLogons {
            get {
                return this.GoodLogonsField;
            }
            set {
                if ((this.GoodLogonsField.Equals(value) != true)) {
                    this.GoodLogonsField = value;
                    this.RaisePropertyChanged("GoodLogons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLastConfirmer {
            get {
                return this.IsLastConfirmerField;
            }
            set {
                if ((this.IsLastConfirmerField.Equals(value) != true)) {
                    this.IsLastConfirmerField = value;
                    this.RaisePropertyChanged("IsLastConfirmer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LimitedAccess {
            get {
                return this.LimitedAccessField;
            }
            set {
                if ((this.LimitedAccessField.Equals(value) != true)) {
                    this.LimitedAccessField = value;
                    this.RaisePropertyChanged("LimitedAccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double OneTransactionLimit {
            get {
                return this.OneTransactionLimitField;
            }
            set {
                if ((this.OneTransactionLimitField.Equals(value) != true)) {
                    this.OneTransactionLimitField = value;
                    this.RaisePropertyChanged("OneTransactionLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExternalBankingRESTService.OnlineBankingSecServRef.ChangePasswordResult PasswordChangeResult {
            get {
                return this.PasswordChangeResultField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordChangeResultField, value) != true)) {
                    this.PasswordChangeResultField = value;
                    this.RaisePropertyChanged("PasswordChangeResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecondConfirm {
            get {
                return this.SecondConfirmField;
            }
            set {
                if ((this.SecondConfirmField.Equals(value) != true)) {
                    this.SecondConfirmField = value;
                    this.RaisePropertyChanged("SecondConfirm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeOfClient {
            get {
                return this.TypeOfClientField;
            }
            set {
                if ((this.TypeOfClientField.Equals(value) != true)) {
                    this.TypeOfClientField = value;
                    this.RaisePropertyChanged("TypeOfClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ExternalBankingRESTService.OnlineBankingSecServRef.UserGroup> UserGroups {
            get {
                return this.UserGroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserGroupsField, value) != true)) {
                    this.UserGroupsField = value;
                    this.RaisePropertyChanged("UserGroups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExternalBankingRESTService.OnlineBankingSecServRef.UserSecurityInfo UserSecurityInformation {
            get {
                return this.UserSecurityInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.UserSecurityInformationField, value) != true)) {
                    this.UserSecurityInformationField = value;
                    this.RaisePropertyChanged("UserSecurityInformation");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResult", Namespace="http://schemas.datacontract.org/2004/07/ExternalBankingSecurityLibrary")]
    [System.SerializableAttribute()]
    public partial class LoginResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionAMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAuthorizedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExternalBankingRESTService.OnlineBankingSecServRef.LoginResultCode ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SessionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionAM {
            get {
                return this.DescriptionAMField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionAMField, value) != true)) {
                    this.DescriptionAMField = value;
                    this.RaisePropertyChanged("DescriptionAM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAuthorized {
            get {
                return this.IsAuthorizedField;
            }
            set {
                if ((this.IsAuthorizedField.Equals(value) != true)) {
                    this.IsAuthorizedField = value;
                    this.RaisePropertyChanged("IsAuthorized");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExternalBankingRESTService.OnlineBankingSecServRef.LoginResultCode ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SessionID {
            get {
                return this.SessionIDField;
            }
            set {
                if ((this.SessionIDField.Equals(value) != true)) {
                    this.SessionIDField = value;
                    this.RaisePropertyChanged("SessionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangePasswordResult", Namespace="http://schemas.datacontract.org/2004/07/ExternalBankingSecurityLibrary")]
    [System.SerializableAttribute()]
    public partial class ChangePasswordResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionAMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionAM {
            get {
                return this.DescriptionAMField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionAMField, value) != true)) {
                    this.DescriptionAMField = value;
                    this.RaisePropertyChanged("DescriptionAM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsChanged {
            get {
                return this.IsChangedField;
            }
            set {
                if ((this.IsChangedField.Equals(value) != true)) {
                    this.IsChangedField = value;
                    this.RaisePropertyChanged("IsChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSecurityInfo", Namespace="http://schemas.datacontract.org/2004/07/ExternalBankingSecurityLibrary")]
    [System.SerializableAttribute()]
    public partial class UserSecurityInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BadIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BadLogonsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DailyTransactionsLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfRegistrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoodIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoodLogonsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastBadLogonDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastGoodLogonDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double OneTransactionLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PasswordChangeDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PermissionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BadIP {
            get {
                return this.BadIPField;
            }
            set {
                if ((object.ReferenceEquals(this.BadIPField, value) != true)) {
                    this.BadIPField = value;
                    this.RaisePropertyChanged("BadIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BadLogons {
            get {
                return this.BadLogonsField;
            }
            set {
                if ((this.BadLogonsField.Equals(value) != true)) {
                    this.BadLogonsField = value;
                    this.RaisePropertyChanged("BadLogons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DailyTransactionsLimit {
            get {
                return this.DailyTransactionsLimitField;
            }
            set {
                if ((this.DailyTransactionsLimitField.Equals(value) != true)) {
                    this.DailyTransactionsLimitField = value;
                    this.RaisePropertyChanged("DailyTransactionsLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfRegistration {
            get {
                return this.DateOfRegistrationField;
            }
            set {
                if ((this.DateOfRegistrationField.Equals(value) != true)) {
                    this.DateOfRegistrationField = value;
                    this.RaisePropertyChanged("DateOfRegistration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoodIP {
            get {
                return this.GoodIPField;
            }
            set {
                if ((object.ReferenceEquals(this.GoodIPField, value) != true)) {
                    this.GoodIPField = value;
                    this.RaisePropertyChanged("GoodIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GoodLogons {
            get {
                return this.GoodLogonsField;
            }
            set {
                if ((this.GoodLogonsField.Equals(value) != true)) {
                    this.GoodLogonsField = value;
                    this.RaisePropertyChanged("GoodLogons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastBadLogonDate {
            get {
                return this.LastBadLogonDateField;
            }
            set {
                if ((this.LastBadLogonDateField.Equals(value) != true)) {
                    this.LastBadLogonDateField = value;
                    this.RaisePropertyChanged("LastBadLogonDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastGoodLogonDate {
            get {
                return this.LastGoodLogonDateField;
            }
            set {
                if ((this.LastGoodLogonDateField.Equals(value) != true)) {
                    this.LastGoodLogonDateField = value;
                    this.RaisePropertyChanged("LastGoodLogonDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double OneTransactionLimit {
            get {
                return this.OneTransactionLimitField;
            }
            set {
                if ((this.OneTransactionLimitField.Equals(value) != true)) {
                    this.OneTransactionLimitField = value;
                    this.RaisePropertyChanged("OneTransactionLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PasswordChangeDate {
            get {
                return this.PasswordChangeDateField;
            }
            set {
                if ((this.PasswordChangeDateField.Equals(value) != true)) {
                    this.PasswordChangeDateField = value;
                    this.RaisePropertyChanged("PasswordChangeDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Permission {
            get {
                return this.PermissionField;
            }
            set {
                if ((this.PermissionField.Equals(value) != true)) {
                    this.PermissionField = value;
                    this.RaisePropertyChanged("Permission");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserGroup", Namespace="http://schemas.datacontract.org/2004/07/ExternalBankingSecurityLibrary")]
    [System.SerializableAttribute()]
    public partial class UserGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupID {
            get {
                return this.GroupIDField;
            }
            set {
                if ((this.GroupIDField.Equals(value) != true)) {
                    this.GroupIDField = value;
                    this.RaisePropertyChanged("GroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupNumber {
            get {
                return this.GroupNumberField;
            }
            set {
                if ((this.GroupNumberField.Equals(value) != true)) {
                    this.GroupNumberField = value;
                    this.RaisePropertyChanged("GroupNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResultCode", Namespace="http://schemas.datacontract.org/2004/07/ExternalBankingSecurityLibrary")]
    public enum LoginResultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChangePassword = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationFailed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OtherError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CorrectLogin = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataNotVerified = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmptyData = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EnterenceDenied = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Locked15min = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthorizationObjectNotFoundInCache = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthorizationObjectCanNotBeNull = 9,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangePasswordInfo", Namespace="http://schemas.datacontract.org/2004/07/ExternalBankingSecurityLibrary")]
    [System.SerializableAttribute()]
    public partial class ChangePasswordInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RetypePasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IpAddress {
            get {
                return this.IpAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IpAddressField, value) != true)) {
                    this.IpAddressField = value;
                    this.RaisePropertyChanged("IpAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewPassword {
            get {
                return this.NewPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.NewPasswordField, value) != true)) {
                    this.NewPasswordField = value;
                    this.RaisePropertyChanged("NewPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RetypePassword {
            get {
                return this.RetypePasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.RetypePasswordField, value) != true)) {
                    this.RetypePasswordField = value;
                    this.RaisePropertyChanged("RetypePassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OnlineBankingSecServRef.IOnlineBankingSecurity")]
    public interface IOnlineBankingSecurity {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurity/AuthorizeMobileUser", ReplyAction="http://tempuri.org/IOnlineBankingSecurity/AuthorizeMobileUserResponse")]
        ExternalBankingRESTService.OnlineBankingSecServRef.OnlineBankingUser AuthorizeMobileUser(ExternalBankingRESTService.OnlineBankingSecServRef.LoginInfo lInfo, byte lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurity/AuthorizeMobileUser", ReplyAction="http://tempuri.org/IOnlineBankingSecurity/AuthorizeMobileUserResponse")]
        System.Threading.Tasks.Task<ExternalBankingRESTService.OnlineBankingSecServRef.OnlineBankingUser> AuthorizeMobileUserAsync(ExternalBankingRESTService.OnlineBankingSecServRef.LoginInfo lInfo, byte lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurity/AuthorizeUserByUserPassword", ReplyAction="http://tempuri.org/IOnlineBankingSecurity/AuthorizeUserByUserPasswordResponse")]
        ExternalBankingRESTService.OnlineBankingSecServRef.OnlineBankingUser AuthorizeUserByUserPassword(ExternalBankingRESTService.OnlineBankingSecServRef.LoginInfo lInfo, byte lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurity/AuthorizeUserByUserPassword", ReplyAction="http://tempuri.org/IOnlineBankingSecurity/AuthorizeUserByUserPasswordResponse")]
        System.Threading.Tasks.Task<ExternalBankingRESTService.OnlineBankingSecServRef.OnlineBankingUser> AuthorizeUserByUserPasswordAsync(ExternalBankingRESTService.OnlineBankingSecServRef.LoginInfo lInfo, byte lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurity/AuthorizeUserByToken", ReplyAction="http://tempuri.org/IOnlineBankingSecurity/AuthorizeUserByTokenResponse")]
        ExternalBankingRESTService.OnlineBankingSecServRef.OnlineBankingUser AuthorizeUserByToken(ExternalBankingRESTService.OnlineBankingSecServRef.LoginInfo lInfo, ExternalBankingRESTService.OnlineBankingSecServRef.LoginResult lResult, byte lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurity/AuthorizeUserByToken", ReplyAction="http://tempuri.org/IOnlineBankingSecurity/AuthorizeUserByTokenResponse")]
        System.Threading.Tasks.Task<ExternalBankingRESTService.OnlineBankingSecServRef.OnlineBankingUser> AuthorizeUserByTokenAsync(ExternalBankingRESTService.OnlineBankingSecServRef.LoginInfo lInfo, ExternalBankingRESTService.OnlineBankingSecServRef.LoginResult lResult, byte lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurity/ChangeUserPassword", ReplyAction="http://tempuri.org/IOnlineBankingSecurity/ChangeUserPasswordResponse")]
        ExternalBankingRESTService.OnlineBankingSecServRef.OnlineBankingUser ChangeUserPassword(ExternalBankingRESTService.OnlineBankingSecServRef.ChangePasswordInfo cpInfo, string sessionID, byte lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurity/ChangeUserPassword", ReplyAction="http://tempuri.org/IOnlineBankingSecurity/ChangeUserPasswordResponse")]
        System.Threading.Tasks.Task<ExternalBankingRESTService.OnlineBankingSecServRef.OnlineBankingUser> ChangeUserPasswordAsync(ExternalBankingRESTService.OnlineBankingSecServRef.ChangePasswordInfo cpInfo, string sessionID, byte lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurity/CheckAuthorization", ReplyAction="http://tempuri.org/IOnlineBankingSecurity/CheckAuthorizationResponse")]
        ExternalBankingRESTService.OnlineBankingSecServRef.OnlineBankingUser CheckAuthorization(string sessionID, byte lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurity/CheckAuthorization", ReplyAction="http://tempuri.org/IOnlineBankingSecurity/CheckAuthorizationResponse")]
        System.Threading.Tasks.Task<ExternalBankingRESTService.OnlineBankingSecServRef.OnlineBankingUser> CheckAuthorizationAsync(string sessionID, byte lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurity/SingData", ReplyAction="http://tempuri.org/IOnlineBankingSecurity/SingDataResponse")]
        bool SingData(string sessionID, string otp, System.Collections.Generic.Dictionary<string, string> dfs, byte lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurity/SingData", ReplyAction="http://tempuri.org/IOnlineBankingSecurity/SingDataResponse")]
        System.Threading.Tasks.Task<bool> SingDataAsync(string sessionID, string otp, System.Collections.Generic.Dictionary<string, string> dfs, byte lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurity/VerifyToken", ReplyAction="http://tempuri.org/IOnlineBankingSecurity/VerifyTokenResponse")]
        bool VerifyToken(string sessionID, string otp, string ipAddress, byte lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurity/VerifyToken", ReplyAction="http://tempuri.org/IOnlineBankingSecurity/VerifyTokenResponse")]
        System.Threading.Tasks.Task<bool> VerifyTokenAsync(string sessionID, string otp, string ipAddress, byte lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurity/CheckRegistrationCode", ReplyAction="http://tempuri.org/IOnlineBankingSecurity/CheckRegistrationCodeResponse")]
        string CheckRegistrationCode(string registrationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBankingSecurity/CheckRegistrationCode", ReplyAction="http://tempuri.org/IOnlineBankingSecurity/CheckRegistrationCodeResponse")]
        System.Threading.Tasks.Task<string> CheckRegistrationCodeAsync(string registrationCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOnlineBankingSecurityChannel : ExternalBankingRESTService.OnlineBankingSecServRef.IOnlineBankingSecurity, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OnlineBankingSecurityClient : System.ServiceModel.ClientBase<ExternalBankingRESTService.OnlineBankingSecServRef.IOnlineBankingSecurity>, ExternalBankingRESTService.OnlineBankingSecServRef.IOnlineBankingSecurity {
        
        public OnlineBankingSecurityClient() {
        }
        
        public OnlineBankingSecurityClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OnlineBankingSecurityClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlineBankingSecurityClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlineBankingSecurityClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ExternalBankingRESTService.OnlineBankingSecServRef.OnlineBankingUser AuthorizeMobileUser(ExternalBankingRESTService.OnlineBankingSecServRef.LoginInfo lInfo, byte lang) {
            return base.Channel.AuthorizeMobileUser(lInfo, lang);
        }
        
        public System.Threading.Tasks.Task<ExternalBankingRESTService.OnlineBankingSecServRef.OnlineBankingUser> AuthorizeMobileUserAsync(ExternalBankingRESTService.OnlineBankingSecServRef.LoginInfo lInfo, byte lang) {
            return base.Channel.AuthorizeMobileUserAsync(lInfo, lang);
        }
        
        public ExternalBankingRESTService.OnlineBankingSecServRef.OnlineBankingUser AuthorizeUserByUserPassword(ExternalBankingRESTService.OnlineBankingSecServRef.LoginInfo lInfo, byte lang) {
            return base.Channel.AuthorizeUserByUserPassword(lInfo, lang);
        }
        
        public System.Threading.Tasks.Task<ExternalBankingRESTService.OnlineBankingSecServRef.OnlineBankingUser> AuthorizeUserByUserPasswordAsync(ExternalBankingRESTService.OnlineBankingSecServRef.LoginInfo lInfo, byte lang) {
            return base.Channel.AuthorizeUserByUserPasswordAsync(lInfo, lang);
        }
        
        public ExternalBankingRESTService.OnlineBankingSecServRef.OnlineBankingUser AuthorizeUserByToken(ExternalBankingRESTService.OnlineBankingSecServRef.LoginInfo lInfo, ExternalBankingRESTService.OnlineBankingSecServRef.LoginResult lResult, byte lang) {
            return base.Channel.AuthorizeUserByToken(lInfo, lResult, lang);
        }
        
        public System.Threading.Tasks.Task<ExternalBankingRESTService.OnlineBankingSecServRef.OnlineBankingUser> AuthorizeUserByTokenAsync(ExternalBankingRESTService.OnlineBankingSecServRef.LoginInfo lInfo, ExternalBankingRESTService.OnlineBankingSecServRef.LoginResult lResult, byte lang) {
            return base.Channel.AuthorizeUserByTokenAsync(lInfo, lResult, lang);
        }
        
        public ExternalBankingRESTService.OnlineBankingSecServRef.OnlineBankingUser ChangeUserPassword(ExternalBankingRESTService.OnlineBankingSecServRef.ChangePasswordInfo cpInfo, string sessionID, byte lang) {
            return base.Channel.ChangeUserPassword(cpInfo, sessionID, lang);
        }
        
        public System.Threading.Tasks.Task<ExternalBankingRESTService.OnlineBankingSecServRef.OnlineBankingUser> ChangeUserPasswordAsync(ExternalBankingRESTService.OnlineBankingSecServRef.ChangePasswordInfo cpInfo, string sessionID, byte lang) {
            return base.Channel.ChangeUserPasswordAsync(cpInfo, sessionID, lang);
        }
        
        public ExternalBankingRESTService.OnlineBankingSecServRef.OnlineBankingUser CheckAuthorization(string sessionID, byte lang) {
            return base.Channel.CheckAuthorization(sessionID, lang);
        }
        
        public System.Threading.Tasks.Task<ExternalBankingRESTService.OnlineBankingSecServRef.OnlineBankingUser> CheckAuthorizationAsync(string sessionID, byte lang) {
            return base.Channel.CheckAuthorizationAsync(sessionID, lang);
        }
        
        public bool SingData(string sessionID, string otp, System.Collections.Generic.Dictionary<string, string> dfs, byte lang) {
            return base.Channel.SingData(sessionID, otp, dfs, lang);
        }
        
        public System.Threading.Tasks.Task<bool> SingDataAsync(string sessionID, string otp, System.Collections.Generic.Dictionary<string, string> dfs, byte lang) {
            return base.Channel.SingDataAsync(sessionID, otp, dfs, lang);
        }
        
        public bool VerifyToken(string sessionID, string otp, string ipAddress, byte lang) {
            return base.Channel.VerifyToken(sessionID, otp, ipAddress, lang);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyTokenAsync(string sessionID, string otp, string ipAddress, byte lang) {
            return base.Channel.VerifyTokenAsync(sessionID, otp, ipAddress, lang);
        }
        
        public string CheckRegistrationCode(string registrationCode) {
            return base.Channel.CheckRegistrationCode(registrationCode);
        }
        
        public System.Threading.Tasks.Task<string> CheckRegistrationCodeAsync(string registrationCode) {
            return base.Channel.CheckRegistrationCodeAsync(registrationCode);
        }
    }
}
