//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/ExternalBanking")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort AccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountTypeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort AccountType {
            get {
                return this.AccountTypeField;
            }
            set {
                if ((this.AccountTypeField.Equals(value) != true)) {
                    this.AccountTypeField = value;
                    this.RaisePropertyChanged("AccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountTypeDescription {
            get {
                return this.AccountTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountTypeDescriptionField, value) != true)) {
                    this.AccountTypeDescriptionField = value;
                    this.RaisePropertyChanged("AccountTypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountStatement", Namespace="http://schemas.datacontract.org/2004/07/ExternalBanking")]
    [System.SerializableAttribute()]
    public partial class AccountStatement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FinalBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double InitialBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalCreditAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalDebitAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfService1.ServiceReference1.AccountStatementDetail[] TransactionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FinalBalance {
            get {
                return this.FinalBalanceField;
            }
            set {
                if ((this.FinalBalanceField.Equals(value) != true)) {
                    this.FinalBalanceField = value;
                    this.RaisePropertyChanged("FinalBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double InitialBalance {
            get {
                return this.InitialBalanceField;
            }
            set {
                if ((this.InitialBalanceField.Equals(value) != true)) {
                    this.InitialBalanceField = value;
                    this.RaisePropertyChanged("InitialBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalCreditAmount {
            get {
                return this.TotalCreditAmountField;
            }
            set {
                if ((this.TotalCreditAmountField.Equals(value) != true)) {
                    this.TotalCreditAmountField = value;
                    this.RaisePropertyChanged("TotalCreditAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalDebitAmount {
            get {
                return this.TotalDebitAmountField;
            }
            set {
                if ((this.TotalDebitAmountField.Equals(value) != true)) {
                    this.TotalDebitAmountField = value;
                    this.RaisePropertyChanged("TotalDebitAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfService1.ServiceReference1.AccountStatementDetail[] Transactions {
            get {
                return this.TransactionsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionsField, value) != true)) {
                    this.TransactionsField = value;
                    this.RaisePropertyChanged("Transactions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountStatementDetail", Namespace="http://schemas.datacontract.org/2004/07/ExternalBanking")]
    [System.SerializableAttribute()]
    public partial class AccountStatementDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountBaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorrespondentAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char DebitCreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransactionDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AmountBase {
            get {
                return this.AmountBaseField;
            }
            set {
                if ((this.AmountBaseField.Equals(value) != true)) {
                    this.AmountBaseField = value;
                    this.RaisePropertyChanged("AmountBase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorrespondentAccount {
            get {
                return this.CorrespondentAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrespondentAccountField, value) != true)) {
                    this.CorrespondentAccountField = value;
                    this.RaisePropertyChanged("CorrespondentAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char DebitCredit {
            get {
                return this.DebitCreditField;
            }
            set {
                if ((this.DebitCreditField.Equals(value) != true)) {
                    this.DebitCreditField = value;
                    this.RaisePropertyChanged("DebitCredit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransactionDate {
            get {
                return this.TransactionDateField;
            }
            set {
                if ((this.TransactionDateField.Equals(value) != true)) {
                    this.TransactionDateField = value;
                    this.RaisePropertyChanged("TransactionDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Card", Namespace="http://schemas.datacontract.org/2004/07/ExternalBanking")]
    [System.SerializableAttribute()]
    public partial class Card : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfService1.ServiceReference1.Account CardAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CardSystemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfService1.ServiceReference1.CardCreditLine CreditLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MainCardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ValidationDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfService1.ServiceReference1.Account CardAccount {
            get {
                return this.CardAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.CardAccountField, value) != true)) {
                    this.CardAccountField = value;
                    this.RaisePropertyChanged("CardAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CardSystem {
            get {
                return this.CardSystemField;
            }
            set {
                if ((this.CardSystemField.Equals(value) != true)) {
                    this.CardSystemField = value;
                    this.RaisePropertyChanged("CardSystem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardType {
            get {
                return this.CardTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CardTypeField, value) != true)) {
                    this.CardTypeField = value;
                    this.RaisePropertyChanged("CardType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfService1.ServiceReference1.CardCreditLine CreditLine {
            get {
                return this.CreditLineField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditLineField, value) != true)) {
                    this.CreditLineField = value;
                    this.RaisePropertyChanged("CreditLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainCardNumber {
            get {
                return this.MainCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MainCardNumberField, value) != true)) {
                    this.MainCardNumberField = value;
                    this.RaisePropertyChanged("MainCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ValidationDate {
            get {
                return this.ValidationDateField;
            }
            set {
                if ((this.ValidationDateField.Equals(value) != true)) {
                    this.ValidationDateField = value;
                    this.RaisePropertyChanged("ValidationDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardCreditLine", Namespace="http://schemas.datacontract.org/2004/07/ExternalBanking")]
    [System.SerializableAttribute()]
    public partial class CardCreditLine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CurrentCapitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double StartCapitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CurrentCapital {
            get {
                return this.CurrentCapitalField;
            }
            set {
                if ((this.CurrentCapitalField.Equals(value) != true)) {
                    this.CurrentCapitalField = value;
                    this.RaisePropertyChanged("CurrentCapital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double StartCapital {
            get {
                return this.StartCapitalField;
            }
            set {
                if ((this.StartCapitalField.Equals(value) != true)) {
                    this.StartCapitalField = value;
                    this.RaisePropertyChanged("StartCapital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardStatement", Namespace="http://schemas.datacontract.org/2004/07/ExternalBanking")]
    [System.SerializableAttribute()]
    public partial class CardStatement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FinalBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double InitialBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalCreditAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalDebitAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfService1.ServiceReference1.CardStatementDetail[] TransactionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FinalBalance {
            get {
                return this.FinalBalanceField;
            }
            set {
                if ((this.FinalBalanceField.Equals(value) != true)) {
                    this.FinalBalanceField = value;
                    this.RaisePropertyChanged("FinalBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double InitialBalance {
            get {
                return this.InitialBalanceField;
            }
            set {
                if ((this.InitialBalanceField.Equals(value) != true)) {
                    this.InitialBalanceField = value;
                    this.RaisePropertyChanged("InitialBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalCreditAmount {
            get {
                return this.TotalCreditAmountField;
            }
            set {
                if ((this.TotalCreditAmountField.Equals(value) != true)) {
                    this.TotalCreditAmountField = value;
                    this.RaisePropertyChanged("TotalCreditAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalDebitAmount {
            get {
                return this.TotalDebitAmountField;
            }
            set {
                if ((this.TotalDebitAmountField.Equals(value) != true)) {
                    this.TotalDebitAmountField = value;
                    this.RaisePropertyChanged("TotalDebitAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfService1.ServiceReference1.CardStatementDetail[] Transactions {
            get {
                return this.TransactionsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionsField, value) != true)) {
                    this.TransactionsField = value;
                    this.RaisePropertyChanged("Transactions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardStatementDetail", Namespace="http://schemas.datacontract.org/2004/07/ExternalBanking")]
    [System.SerializableAttribute()]
    public partial class CardStatementDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CommissionFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte DebitCreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double OperationAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationCardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OperationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransactionDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CommissionFee {
            get {
                return this.CommissionFeeField;
            }
            set {
                if ((this.CommissionFeeField.Equals(value) != true)) {
                    this.CommissionFeeField = value;
                    this.RaisePropertyChanged("CommissionFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte DebitCredit {
            get {
                return this.DebitCreditField;
            }
            set {
                if ((this.DebitCreditField.Equals(value) != true)) {
                    this.DebitCreditField = value;
                    this.RaisePropertyChanged("DebitCredit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double OperationAmount {
            get {
                return this.OperationAmountField;
            }
            set {
                if ((this.OperationAmountField.Equals(value) != true)) {
                    this.OperationAmountField = value;
                    this.RaisePropertyChanged("OperationAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationCardNumber {
            get {
                return this.OperationCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationCardNumberField, value) != true)) {
                    this.OperationCardNumberField = value;
                    this.RaisePropertyChanged("OperationCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationCurrency {
            get {
                return this.OperationCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationCurrencyField, value) != true)) {
                    this.OperationCurrencyField = value;
                    this.RaisePropertyChanged("OperationCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OperationDate {
            get {
                return this.OperationDateField;
            }
            set {
                if ((this.OperationDateField.Equals(value) != true)) {
                    this.OperationDateField = value;
                    this.RaisePropertyChanged("OperationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransactionDate {
            get {
                return this.TransactionDateField;
            }
            set {
                if ((this.TransactionDateField.Equals(value) != true)) {
                    this.TransactionDateField = value;
                    this.RaisePropertyChanged("TransactionDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Loan", Namespace="http://schemas.datacontract.org/2004/07/ExternalBanking")]
    [System.SerializableAttribute()]
    public partial class Loan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CurrentCapitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CurrentRateValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float InterestRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoanTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanTypeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QualityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QualityDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double StartCapitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CurrentCapital {
            get {
                return this.CurrentCapitalField;
            }
            set {
                if ((this.CurrentCapitalField.Equals(value) != true)) {
                    this.CurrentCapitalField = value;
                    this.RaisePropertyChanged("CurrentCapital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CurrentRateValue {
            get {
                return this.CurrentRateValueField;
            }
            set {
                if ((this.CurrentRateValueField.Equals(value) != true)) {
                    this.CurrentRateValueField = value;
                    this.RaisePropertyChanged("CurrentRateValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float InterestRate {
            get {
                return this.InterestRateField;
            }
            set {
                if ((this.InterestRateField.Equals(value) != true)) {
                    this.InterestRateField = value;
                    this.RaisePropertyChanged("InterestRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanAccount {
            get {
                return this.LoanAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanAccountField, value) != true)) {
                    this.LoanAccountField = value;
                    this.RaisePropertyChanged("LoanAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoanType {
            get {
                return this.LoanTypeField;
            }
            set {
                if ((this.LoanTypeField.Equals(value) != true)) {
                    this.LoanTypeField = value;
                    this.RaisePropertyChanged("LoanType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanTypeDescription {
            get {
                return this.LoanTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanTypeDescriptionField, value) != true)) {
                    this.LoanTypeDescriptionField = value;
                    this.RaisePropertyChanged("LoanTypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quality {
            get {
                return this.QualityField;
            }
            set {
                if ((this.QualityField.Equals(value) != true)) {
                    this.QualityField = value;
                    this.RaisePropertyChanged("Quality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QualityDescription {
            get {
                return this.QualityDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.QualityDescriptionField, value) != true)) {
                    this.QualityDescriptionField = value;
                    this.RaisePropertyChanged("QualityDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double StartCapital {
            get {
                return this.StartCapitalField;
            }
            set {
                if ((this.StartCapitalField.Equals(value) != true)) {
                    this.StartCapitalField = value;
                    this.RaisePropertyChanged("StartCapital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IExternalBankingService")]
    public interface IExternalBankingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExternalBankingService/GetAccount", ReplyAction="http://tempuri.org/IExternalBankingService/GetAccountResponse")]
        WcfService1.ServiceReference1.Account GetAccount(ulong accountNumber, byte language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExternalBankingService/GetAccount", ReplyAction="http://tempuri.org/IExternalBankingService/GetAccountResponse")]
        System.Threading.Tasks.Task<WcfService1.ServiceReference1.Account> GetAccountAsync(ulong accountNumber, byte language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExternalBankingService/GetAccounts", ReplyAction="http://tempuri.org/IExternalBankingService/GetAccountsResponse")]
        WcfService1.ServiceReference1.Account[] GetAccounts(ulong customerNumber, byte language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExternalBankingService/GetAccounts", ReplyAction="http://tempuri.org/IExternalBankingService/GetAccountsResponse")]
        System.Threading.Tasks.Task<WcfService1.ServiceReference1.Account[]> GetAccountsAsync(ulong customerNumber, byte language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExternalBankingService/AccountStatement", ReplyAction="http://tempuri.org/IExternalBankingService/AccountStatementResponse")]
        WcfService1.ServiceReference1.AccountStatement AccountStatement(WcfService1.ServiceReference1.Account account, System.DateTime dateFrom, System.DateTime dateTo, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExternalBankingService/AccountStatement", ReplyAction="http://tempuri.org/IExternalBankingService/AccountStatementResponse")]
        System.Threading.Tasks.Task<WcfService1.ServiceReference1.AccountStatement> AccountStatementAsync(WcfService1.ServiceReference1.Account account, System.DateTime dateFrom, System.DateTime dateTo, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExternalBankingService/GetCard", ReplyAction="http://tempuri.org/IExternalBankingService/GetCardResponse")]
        WcfService1.ServiceReference1.Card GetCard(string cardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExternalBankingService/GetCard", ReplyAction="http://tempuri.org/IExternalBankingService/GetCardResponse")]
        System.Threading.Tasks.Task<WcfService1.ServiceReference1.Card> GetCardAsync(string cardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExternalBankingService/GetCards", ReplyAction="http://tempuri.org/IExternalBankingService/GetCardsResponse")]
        WcfService1.ServiceReference1.Card[] GetCards();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExternalBankingService/GetCards", ReplyAction="http://tempuri.org/IExternalBankingService/GetCardsResponse")]
        System.Threading.Tasks.Task<WcfService1.ServiceReference1.Card[]> GetCardsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExternalBankingService/GetCardStatement", ReplyAction="http://tempuri.org/IExternalBankingService/GetCardStatementResponse")]
        WcfService1.ServiceReference1.CardStatement GetCardStatement(string cardNumber, System.DateTime dateFrom, System.DateTime dateTo, byte language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExternalBankingService/GetCardStatement", ReplyAction="http://tempuri.org/IExternalBankingService/GetCardStatementResponse")]
        System.Threading.Tasks.Task<WcfService1.ServiceReference1.CardStatement> GetCardStatementAsync(string cardNumber, System.DateTime dateFrom, System.DateTime dateTo, byte language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExternalBankingService/GetLoan", ReplyAction="http://tempuri.org/IExternalBankingService/GetLoanResponse")]
        WcfService1.ServiceReference1.Loan GetLoan(long productId, byte language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExternalBankingService/GetLoan", ReplyAction="http://tempuri.org/IExternalBankingService/GetLoanResponse")]
        System.Threading.Tasks.Task<WcfService1.ServiceReference1.Loan> GetLoanAsync(long productId, byte language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExternalBankingService/GetLoans", ReplyAction="http://tempuri.org/IExternalBankingService/GetLoansResponse")]
        WcfService1.ServiceReference1.Loan[] GetLoans(byte language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExternalBankingService/GetLoans", ReplyAction="http://tempuri.org/IExternalBankingService/GetLoansResponse")]
        System.Threading.Tasks.Task<WcfService1.ServiceReference1.Loan[]> GetLoansAsync(byte language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExternalBankingService/UpdateHttpContex", ReplyAction="http://tempuri.org/IExternalBankingService/UpdateHttpContexResponse")]
        void UpdateHttpContex();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExternalBankingService/UpdateHttpContex", ReplyAction="http://tempuri.org/IExternalBankingService/UpdateHttpContexResponse")]
        System.Threading.Tasks.Task UpdateHttpContexAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExternalBankingServiceChannel : global::WcfService1.ServiceReference1.IExternalBankingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExternalBankingServiceClient : System.ServiceModel.ClientBase<global::WcfService1.ServiceReference1.IExternalBankingService>, global::WcfService1.ServiceReference1.IExternalBankingService {
        
        public ExternalBankingServiceClient() {
        }
        
        public ExternalBankingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExternalBankingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExternalBankingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExternalBankingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfService1.ServiceReference1.Account GetAccount(ulong accountNumber, byte language) {
            return base.Channel.GetAccount(accountNumber, language);
        }
        
        public System.Threading.Tasks.Task<WcfService1.ServiceReference1.Account> GetAccountAsync(ulong accountNumber, byte language) {
            return base.Channel.GetAccountAsync(accountNumber, language);
        }
        
        public WcfService1.ServiceReference1.Account[] GetAccounts(ulong customerNumber, byte language) {
            return base.Channel.GetAccounts(customerNumber, language);
        }
        
        public System.Threading.Tasks.Task<WcfService1.ServiceReference1.Account[]> GetAccountsAsync(ulong customerNumber, byte language) {
            return base.Channel.GetAccountsAsync(customerNumber, language);
        }
        
        public WcfService1.ServiceReference1.AccountStatement AccountStatement(WcfService1.ServiceReference1.Account account, System.DateTime dateFrom, System.DateTime dateTo, string language) {
            return base.Channel.AccountStatement(account, dateFrom, dateTo, language);
        }
        
        public System.Threading.Tasks.Task<WcfService1.ServiceReference1.AccountStatement> AccountStatementAsync(WcfService1.ServiceReference1.Account account, System.DateTime dateFrom, System.DateTime dateTo, string language) {
            return base.Channel.AccountStatementAsync(account, dateFrom, dateTo, language);
        }
        
        public WcfService1.ServiceReference1.Card GetCard(string cardNumber) {
            return base.Channel.GetCard(cardNumber);
        }
        
        public System.Threading.Tasks.Task<WcfService1.ServiceReference1.Card> GetCardAsync(string cardNumber) {
            return base.Channel.GetCardAsync(cardNumber);
        }
        
        public WcfService1.ServiceReference1.Card[] GetCards() {
            return base.Channel.GetCards();
        }
        
        public System.Threading.Tasks.Task<WcfService1.ServiceReference1.Card[]> GetCardsAsync() {
            return base.Channel.GetCardsAsync();
        }
        
        public WcfService1.ServiceReference1.CardStatement GetCardStatement(string cardNumber, System.DateTime dateFrom, System.DateTime dateTo, byte language) {
            return base.Channel.GetCardStatement(cardNumber, dateFrom, dateTo, language);
        }
        
        public System.Threading.Tasks.Task<WcfService1.ServiceReference1.CardStatement> GetCardStatementAsync(string cardNumber, System.DateTime dateFrom, System.DateTime dateTo, byte language) {
            return base.Channel.GetCardStatementAsync(cardNumber, dateFrom, dateTo, language);
        }
        
        public WcfService1.ServiceReference1.Loan GetLoan(long productId, byte language) {
            return base.Channel.GetLoan(productId, language);
        }
        
        public System.Threading.Tasks.Task<WcfService1.ServiceReference1.Loan> GetLoanAsync(long productId, byte language) {
            return base.Channel.GetLoanAsync(productId, language);
        }
        
        public WcfService1.ServiceReference1.Loan[] GetLoans(byte language) {
            return base.Channel.GetLoans(language);
        }
        
        public System.Threading.Tasks.Task<WcfService1.ServiceReference1.Loan[]> GetLoansAsync(byte language) {
            return base.Channel.GetLoansAsync(language);
        }
        
        public void UpdateHttpContex() {
            base.Channel.UpdateHttpContex();
        }
        
        public System.Threading.Tasks.Task UpdateHttpContexAsync() {
            return base.Channel.UpdateHttpContexAsync();
        }
    }
}
