//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExternalBankingRESTService.ContractServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contract", Namespace="http://schemas.datacontract.org/2004/07/ContractService")]
    [System.SerializableAttribute()]
    public partial class Contract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AttachDocTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte AttachFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AttachSourceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContractNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FooterHeightForContractsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ExternalBankingRESTService.ContractServiceReference.KeyValuePairOfstringstring> FormulasListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ExternalBankingRESTService.ContractServiceReference.StringKeyValue> ParametersListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AttachDocType {
            get {
                return this.AttachDocTypeField;
            }
            set {
                if ((this.AttachDocTypeField.Equals(value) != true)) {
                    this.AttachDocTypeField = value;
                    this.RaisePropertyChanged("AttachDocType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte AttachFile {
            get {
                return this.AttachFileField;
            }
            set {
                if ((this.AttachFileField.Equals(value) != true)) {
                    this.AttachFileField = value;
                    this.RaisePropertyChanged("AttachFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AttachSourceType {
            get {
                return this.AttachSourceTypeField;
            }
            set {
                if ((this.AttachSourceTypeField.Equals(value) != true)) {
                    this.AttachSourceTypeField = value;
                    this.RaisePropertyChanged("AttachSourceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractName {
            get {
                return this.ContractNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractNameField, value) != true)) {
                    this.ContractNameField = value;
                    this.RaisePropertyChanged("ContractName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocID {
            get {
                return this.DocIDField;
            }
            set {
                if ((this.DocIDField.Equals(value) != true)) {
                    this.DocIDField = value;
                    this.RaisePropertyChanged("DocID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FooterHeightForContracts {
            get {
                return this.FooterHeightForContractsField;
            }
            set {
                if ((this.FooterHeightForContractsField.Equals(value) != true)) {
                    this.FooterHeightForContractsField = value;
                    this.RaisePropertyChanged("FooterHeightForContracts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ExternalBankingRESTService.ContractServiceReference.KeyValuePairOfstringstring> FormulasList {
            get {
                return this.FormulasListField;
            }
            set {
                if ((object.ReferenceEquals(this.FormulasListField, value) != true)) {
                    this.FormulasListField = value;
                    this.RaisePropertyChanged("FormulasList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ExternalBankingRESTService.ContractServiceReference.StringKeyValue> ParametersList {
            get {
                return this.ParametersListField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersListField, value) != true)) {
                    this.ParametersListField = value;
                    this.RaisePropertyChanged("ParametersList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string content {
            get {
                return this.contentField;
            }
            set {
                if ((object.ReferenceEquals(this.contentField, value) != true)) {
                    this.contentField = value;
                    this.RaisePropertyChanged("content");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValuePairOfstringstring", Namespace="http://schemas.datacontract.org/2004/07/System.Collections.Generic")]
    [System.SerializableAttribute()]
    public partial struct KeyValuePairOfstringstring : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string keyField;
        
        private string valueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                if ((object.ReferenceEquals(this.keyField, value) != true)) {
                    this.keyField = value;
                    this.RaisePropertyChanged("key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StringKeyValue", Namespace="http://schemas.datacontract.org/2004/07/ContractService")]
    [System.SerializableAttribute()]
    public partial class StringKeyValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Version", Namespace="http://schemas.datacontract.org/2004/07/System")]
    [System.SerializableAttribute()]
    public partial class Version : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int _BuildField;
        
        private int _MajorField;
        
        private int _MinorField;
        
        private int _RevisionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _Build {
            get {
                return this._BuildField;
            }
            set {
                if ((this._BuildField.Equals(value) != true)) {
                    this._BuildField = value;
                    this.RaisePropertyChanged("_Build");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _Major {
            get {
                return this._MajorField;
            }
            set {
                if ((this._MajorField.Equals(value) != true)) {
                    this._MajorField = value;
                    this.RaisePropertyChanged("_Major");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _Minor {
            get {
                return this._MinorField;
            }
            set {
                if ((this._MinorField.Equals(value) != true)) {
                    this._MinorField = value;
                    this.RaisePropertyChanged("_Minor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _Revision {
            get {
                return this._RevisionField;
            }
            set {
                if ((this._RevisionField.Equals(value) != true)) {
                    this._RevisionField = value;
                    this.RaisePropertyChanged("_Revision");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContractServiceReference.IContractOerationService")]
    public interface IContractOerationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractOerationService/DownloadContract", ReplyAction="http://tempuri.org/IContractOerationService/DownloadContractResponse")]
        byte[] DownloadContract(ExternalBankingRESTService.ContractServiceReference.Contract contract, string userName, string ClientIp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractOerationService/DownloadContract", ReplyAction="http://tempuri.org/IContractOerationService/DownloadContractResponse")]
        System.Threading.Tasks.Task<byte[]> DownloadContractAsync(ExternalBankingRESTService.ContractServiceReference.Contract contract, string userName, string ClientIp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractOerationService/DownloadContractHTML", ReplyAction="http://tempuri.org/IContractOerationService/DownloadContractHTMLResponse")]
        string DownloadContractHTML(ExternalBankingRESTService.ContractServiceReference.Contract contract, string userName, string ClientIp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractOerationService/DownloadContractHTML", ReplyAction="http://tempuri.org/IContractOerationService/DownloadContractHTMLResponse")]
        System.Threading.Tasks.Task<string> DownloadContractHTMLAsync(ExternalBankingRESTService.ContractServiceReference.Contract contract, string userName, string ClientIp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractOerationService/CheckProgramVersion", ReplyAction="http://tempuri.org/IContractOerationService/CheckProgramVersionResponse")]
        bool CheckProgramVersion(short programId, ExternalBankingRESTService.ContractServiceReference.Version version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractOerationService/CheckProgramVersion", ReplyAction="http://tempuri.org/IContractOerationService/CheckProgramVersionResponse")]
        System.Threading.Tasks.Task<bool> CheckProgramVersionAsync(short programId, ExternalBankingRESTService.ContractServiceReference.Version version);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContractOerationServiceChannel : ExternalBankingRESTService.ContractServiceReference.IContractOerationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContractOerationServiceClient : System.ServiceModel.ClientBase<ExternalBankingRESTService.ContractServiceReference.IContractOerationService>, ExternalBankingRESTService.ContractServiceReference.IContractOerationService {
        
        public ContractOerationServiceClient() {
        }
        
        public ContractOerationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContractOerationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractOerationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractOerationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] DownloadContract(ExternalBankingRESTService.ContractServiceReference.Contract contract, string userName, string ClientIp) {
            return base.Channel.DownloadContract(contract, userName, ClientIp);
        }
        
        public System.Threading.Tasks.Task<byte[]> DownloadContractAsync(ExternalBankingRESTService.ContractServiceReference.Contract contract, string userName, string ClientIp) {
            return base.Channel.DownloadContractAsync(contract, userName, ClientIp);
        }
        
        public string DownloadContractHTML(ExternalBankingRESTService.ContractServiceReference.Contract contract, string userName, string ClientIp) {
            return base.Channel.DownloadContractHTML(contract, userName, ClientIp);
        }
        
        public System.Threading.Tasks.Task<string> DownloadContractHTMLAsync(ExternalBankingRESTService.ContractServiceReference.Contract contract, string userName, string ClientIp) {
            return base.Channel.DownloadContractHTMLAsync(contract, userName, ClientIp);
        }
        
        public bool CheckProgramVersion(short programId, ExternalBankingRESTService.ContractServiceReference.Version version) {
            return base.Channel.CheckProgramVersion(programId, version);
        }
        
        public System.Threading.Tasks.Task<bool> CheckProgramVersionAsync(short programId, ExternalBankingRESTService.ContractServiceReference.Version version) {
            return base.Channel.CheckProgramVersionAsync(programId, version);
        }
    }
}
