//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExternalBanking.TokenOperationsServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenOperationsInfo", Namespace="http://schemas.datacontract.org/2004/07/AcbaOnlineSecurityService.Helpers")]
    [System.SerializableAttribute()]
    public partial class TokenOperationsInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OTPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatorID {
            get {
                return this.CreatorIDField;
            }
            set {
                if ((this.CreatorIDField.Equals(value) != true)) {
                    this.CreatorIDField = value;
                    this.RaisePropertyChanged("CreatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GID {
            get {
                return this.GIDField;
            }
            set {
                if ((object.ReferenceEquals(this.GIDField, value) != true)) {
                    this.GIDField = value;
                    this.RaisePropertyChanged("GID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IpAddress {
            get {
                return this.IpAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IpAddressField, value) != true)) {
                    this.IpAddressField = value;
                    this.RaisePropertyChanged("IpAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OTP {
            get {
                return this.OTPField;
            }
            set {
                if ((object.ReferenceEquals(this.OTPField, value) != true)) {
                    this.OTPField = value;
                    this.RaisePropertyChanged("OTP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserDescription {
            get {
                return this.UserDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDescriptionField, value) != true)) {
                    this.UserDescriptionField = value;
                    this.RaisePropertyChanged("UserDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenOperationsResult", Namespace="http://schemas.datacontract.org/2004/07/AcbaOnlineSecurityService.Helpers")]
    [System.SerializableAttribute()]
    public partial class TokenOperationsResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultDescription {
            get {
                return this.ResultDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultDescriptionField, value) != true)) {
                    this.ResultDescriptionField = value;
                    this.RaisePropertyChanged("ResultDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultValue {
            get {
                return this.ResultValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultValueField, value) != true)) {
                    this.ResultValueField = value;
                    this.RaisePropertyChanged("ResultValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TokenOperationsServiceReference.ITokenOperations")]
    public interface ITokenOperations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenOperations/ActivateToken", ReplyAction="http://tempuri.org/ITokenOperations/ActivateTokenResponse")]
        ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult ActivateToken(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenOperations/ActivateToken", ReplyAction="http://tempuri.org/ITokenOperations/ActivateTokenResponse")]
        System.Threading.Tasks.Task<ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult> ActivateTokenAsync(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenOperations/BlockToken", ReplyAction="http://tempuri.org/ITokenOperations/BlockTokenResponse")]
        ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult BlockToken(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenOperations/BlockToken", ReplyAction="http://tempuri.org/ITokenOperations/BlockTokenResponse")]
        System.Threading.Tasks.Task<ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult> BlockTokenAsync(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenOperations/BlockUser", ReplyAction="http://tempuri.org/ITokenOperations/BlockUserResponse")]
        ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult BlockUser(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenOperations/BlockUser", ReplyAction="http://tempuri.org/ITokenOperations/BlockUserResponse")]
        System.Threading.Tasks.Task<ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult> BlockUserAsync(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenOperations/UnlockToken", ReplyAction="http://tempuri.org/ITokenOperations/UnlockTokenResponse")]
        ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult UnlockToken(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenOperations/UnlockToken", ReplyAction="http://tempuri.org/ITokenOperations/UnlockTokenResponse")]
        System.Threading.Tasks.Task<ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult> UnlockTokenAsync(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenOperations/ActivateMobileToken", ReplyAction="http://tempuri.org/ITokenOperations/ActivateMobileTokenResponse")]
        ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult ActivateMobileToken(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenOperations/ActivateMobileToken", ReplyAction="http://tempuri.org/ITokenOperations/ActivateMobileTokenResponse")]
        System.Threading.Tasks.Task<ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult> ActivateMobileTokenAsync(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenOperations/GetPinCode", ReplyAction="http://tempuri.org/ITokenOperations/GetPinCodeResponse")]
        string GetPinCode(string cardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenOperations/GetPinCode", ReplyAction="http://tempuri.org/ITokenOperations/GetPinCodeResponse")]
        System.Threading.Tasks.Task<string> GetPinCodeAsync(string cardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenOperations/ResetUserPasswordManualy", ReplyAction="http://tempuri.org/ITokenOperations/ResetUserPasswordManualyResponse")]
        ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult ResetUserPasswordManualy(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenOperations/ResetUserPasswordManualy", ReplyAction="http://tempuri.org/ITokenOperations/ResetUserPasswordManualyResponse")]
        System.Threading.Tasks.Task<ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult> ResetUserPasswordManualyAsync(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITokenOperationsChannel : ExternalBanking.TokenOperationsServiceReference.ITokenOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TokenOperationsClient : System.ServiceModel.ClientBase<ExternalBanking.TokenOperationsServiceReference.ITokenOperations>, ExternalBanking.TokenOperationsServiceReference.ITokenOperations {
        
        public TokenOperationsClient() {
        }
        
        public TokenOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TokenOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult ActivateToken(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo) {
            return base.Channel.ActivateToken(tInfo);
        }
        
        public System.Threading.Tasks.Task<ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult> ActivateTokenAsync(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo) {
            return base.Channel.ActivateTokenAsync(tInfo);
        }
        
        public ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult BlockToken(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo) {
            return base.Channel.BlockToken(tInfo);
        }
        
        public System.Threading.Tasks.Task<ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult> BlockTokenAsync(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo) {
            return base.Channel.BlockTokenAsync(tInfo);
        }
        
        public ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult BlockUser(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo) {
            return base.Channel.BlockUser(tInfo);
        }
        
        public System.Threading.Tasks.Task<ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult> BlockUserAsync(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo) {
            return base.Channel.BlockUserAsync(tInfo);
        }
        
        public ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult UnlockToken(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo) {
            return base.Channel.UnlockToken(tInfo);
        }
        
        public System.Threading.Tasks.Task<ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult> UnlockTokenAsync(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo) {
            return base.Channel.UnlockTokenAsync(tInfo);
        }
        
        public ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult ActivateMobileToken(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo) {
            return base.Channel.ActivateMobileToken(tInfo);
        }
        
        public System.Threading.Tasks.Task<ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult> ActivateMobileTokenAsync(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo) {
            return base.Channel.ActivateMobileTokenAsync(tInfo);
        }
        
        public string GetPinCode(string cardNumber) {
            return base.Channel.GetPinCode(cardNumber);
        }
        
        public System.Threading.Tasks.Task<string> GetPinCodeAsync(string cardNumber) {
            return base.Channel.GetPinCodeAsync(cardNumber);
        }
        
        public ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult ResetUserPasswordManualy(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo) {
            return base.Channel.ResetUserPasswordManualy(tInfo);
        }
        
        public System.Threading.Tasks.Task<ExternalBanking.TokenOperationsServiceReference.TokenOperationsResult> ResetUserPasswordManualyAsync(ExternalBanking.TokenOperationsServiceReference.TokenOperationsInfo tInfo) {
            return base.Channel.ResetUserPasswordManualyAsync(tInfo);
        }
    }
}
