//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExternalBanking.SMSMessagingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/MessagingLibrary.Services.SMSMessagingSer" +
        "vice")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short userIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short userID {
            get {
                return this.userIDField;
            }
            set {
                if ((this.userIDField.Equals(value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSMessagingSession", Namespace="http://schemas.datacontract.org/2004/07/MessagingLibrary.Services.SMSMessagingSer" +
        "vice")]
    [System.SerializableAttribute()]
    public partial class SMSMessagingSession : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ExternalBanking.SMSMessagingService.SMSMessage> MessagesListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegistrationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ExternalBanking.SMSMessagingService.SMSMessage> MessagesList {
            get {
                return this.MessagesListField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesListField, value) != true)) {
                    this.MessagesListField = value;
                    this.RaisePropertyChanged("MessagesList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegistrationDate {
            get {
                return this.RegistrationDateField;
            }
            set {
                if ((this.RegistrationDateField.Equals(value) != true)) {
                    this.RegistrationDateField = value;
                    this.RaisePropertyChanged("RegistrationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSMessage", Namespace="http://schemas.datacontract.org/2004/07/MessagingLibrary.Services.SMSMessagingSer" +
        "vice")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExternalBanking.SMSMessagingService.OneMessage))]
    public partial class SMSMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ulong CustomerNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ulong IdentityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort SourceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ulong CustomerNumber {
            get {
                return this.CustomerNumberField;
            }
            set {
                if ((this.CustomerNumberField.Equals(value) != true)) {
                    this.CustomerNumberField = value;
                    this.RaisePropertyChanged("CustomerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalId {
            get {
                return this.ExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIdField, value) != true)) {
                    this.ExternalIdField = value;
                    this.RaisePropertyChanged("ExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ulong IdentityId {
            get {
                return this.IdentityIdField;
            }
            set {
                if ((this.IdentityIdField.Equals(value) != true)) {
                    this.IdentityIdField = value;
                    this.RaisePropertyChanged("IdentityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((this.MessageTypeField.Equals(value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort Source {
            get {
                return this.SourceField;
            }
            set {
                if ((this.SourceField.Equals(value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OneMessage", Namespace="http://schemas.datacontract.org/2004/07/MessagingLibrary.Services.SMSMessagingSer" +
        "vice.Models")]
    [System.SerializableAttribute()]
    public partial class OneMessage : ExternalBanking.SMSMessagingService.SMSMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MessageSesionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RegistrationSetNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MessageSesionId {
            get {
                return this.MessageSesionIdField;
            }
            set {
                if ((this.MessageSesionIdField.Equals(value) != true)) {
                    this.MessageSesionIdField = value;
                    this.RaisePropertyChanged("MessageSesionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegDate {
            get {
                return this.RegDateField;
            }
            set {
                if ((this.RegDateField.Equals(value) != true)) {
                    this.RegDateField = value;
                    this.RaisePropertyChanged("RegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegistrationSetNumber {
            get {
                return this.RegistrationSetNumberField;
            }
            set {
                if ((this.RegistrationSetNumberField.Equals(value) != true)) {
                    this.RegistrationSetNumberField = value;
                    this.RaisePropertyChanged("RegistrationSetNumber");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchSMSMessagingSession", Namespace="http://schemas.datacontract.org/2004/07/MessagingLibrary.Services.SMSMessagingSer" +
        "vice")]
    [System.SerializableAttribute()]
    public partial class SearchSMSMessagingSession : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegistrationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegistrationDate {
            get {
                return this.RegistrationDateField;
            }
            set {
                if ((this.RegistrationDateField.Equals(value) != true)) {
                    this.RegistrationDateField = value;
                    this.RaisePropertyChanged("RegistrationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSMessagingService.ISMSMessagingService")]
    public interface ISMSMessagingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/SetCurrentUser", ReplyAction="http://tempuri.org/ISMSMessagingService/SetCurrentUserResponse")]
        void SetCurrentUser(ExternalBanking.SMSMessagingService.User currentUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/SetCurrentUser", ReplyAction="http://tempuri.org/ISMSMessagingService/SetCurrentUserResponse")]
        System.Threading.Tasks.Task SetCurrentUserAsync(ExternalBanking.SMSMessagingService.User currentUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/SetClientIp", ReplyAction="http://tempuri.org/ISMSMessagingService/SetClientIpResponse")]
        void SetClientIp(string clientIp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/SetClientIp", ReplyAction="http://tempuri.org/ISMSMessagingService/SetClientIpResponse")]
        System.Threading.Tasks.Task SetClientIpAsync(string clientIp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/SaveMessagingSession", ReplyAction="http://tempuri.org/ISMSMessagingService/SaveMessagingSessionResponse")]
        void SaveMessagingSession(ExternalBanking.SMSMessagingService.SMSMessagingSession messagingSession);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/SaveMessagingSession", ReplyAction="http://tempuri.org/ISMSMessagingService/SaveMessagingSessionResponse")]
        System.Threading.Tasks.Task SaveMessagingSessionAsync(ExternalBanking.SMSMessagingService.SMSMessagingSession messagingSession);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/ChangeSMSMessagingSessionStatus", ReplyAction="http://tempuri.org/ISMSMessagingService/ChangeSMSMessagingSessionStatusResponse")]
        void ChangeSMSMessagingSessionStatus(uint id, byte newStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/ChangeSMSMessagingSessionStatus", ReplyAction="http://tempuri.org/ISMSMessagingService/ChangeSMSMessagingSessionStatusResponse")]
        System.Threading.Tasks.Task ChangeSMSMessagingSessionStatusAsync(uint id, byte newStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/GetSMSMessagingSessions", ReplyAction="http://tempuri.org/ISMSMessagingService/GetSMSMessagingSessionsResponse")]
        System.Collections.Generic.List<ExternalBanking.SMSMessagingService.SMSMessagingSession> GetSMSMessagingSessions(ExternalBanking.SMSMessagingService.SearchSMSMessagingSession searchParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/GetSMSMessagingSessions", ReplyAction="http://tempuri.org/ISMSMessagingService/GetSMSMessagingSessionsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ExternalBanking.SMSMessagingService.SMSMessagingSession>> GetSMSMessagingSessionsAsync(ExternalBanking.SMSMessagingService.SearchSMSMessagingSession searchParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/DeleteMessagingSession", ReplyAction="http://tempuri.org/ISMSMessagingService/DeleteMessagingSessionResponse")]
        void DeleteMessagingSession(uint id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/DeleteMessagingSession", ReplyAction="http://tempuri.org/ISMSMessagingService/DeleteMessagingSessionResponse")]
        System.Threading.Tasks.Task DeleteMessagingSessionAsync(uint id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/SendMessage", ReplyAction="http://tempuri.org/ISMSMessagingService/SendMessageResponse")]
        void SendMessage(string phoneNumber, ulong customerNumber, string message, int registrationSetNumber, int messageType, ushort source, string externalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/SendMessage", ReplyAction="http://tempuri.org/ISMSMessagingService/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync(string phoneNumber, ulong customerNumber, string message, int registrationSetNumber, int messageType, ushort source, string externalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/SendMessages", ReplyAction="http://tempuri.org/ISMSMessagingService/SendMessagesResponse")]
        void SendMessages(System.Collections.Generic.List<ExternalBanking.SMSMessagingService.SMSMessage> messages, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/SendMessages", ReplyAction="http://tempuri.org/ISMSMessagingService/SendMessagesResponse")]
        System.Threading.Tasks.Task SendMessagesAsync(System.Collections.Generic.List<ExternalBanking.SMSMessagingService.SMSMessage> messages, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/SendOneMessage", ReplyAction="http://tempuri.org/ISMSMessagingService/SendOneMessageResponse")]
        void SendOneMessage(ExternalBanking.SMSMessagingService.OneMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSMessagingService/SendOneMessage", ReplyAction="http://tempuri.org/ISMSMessagingService/SendOneMessageResponse")]
        System.Threading.Tasks.Task SendOneMessageAsync(ExternalBanking.SMSMessagingService.OneMessage message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISMSMessagingServiceChannel : ExternalBanking.SMSMessagingService.ISMSMessagingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSMessagingServiceClient : System.ServiceModel.ClientBase<ExternalBanking.SMSMessagingService.ISMSMessagingService>, ExternalBanking.SMSMessagingService.ISMSMessagingService {
        
        public SMSMessagingServiceClient() {
        }
        
        public SMSMessagingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSMessagingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSMessagingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSMessagingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetCurrentUser(ExternalBanking.SMSMessagingService.User currentUser) {
            base.Channel.SetCurrentUser(currentUser);
        }
        
        public System.Threading.Tasks.Task SetCurrentUserAsync(ExternalBanking.SMSMessagingService.User currentUser) {
            return base.Channel.SetCurrentUserAsync(currentUser);
        }
        
        public void SetClientIp(string clientIp) {
            base.Channel.SetClientIp(clientIp);
        }
        
        public System.Threading.Tasks.Task SetClientIpAsync(string clientIp) {
            return base.Channel.SetClientIpAsync(clientIp);
        }
        
        public void SaveMessagingSession(ExternalBanking.SMSMessagingService.SMSMessagingSession messagingSession) {
            base.Channel.SaveMessagingSession(messagingSession);
        }
        
        public System.Threading.Tasks.Task SaveMessagingSessionAsync(ExternalBanking.SMSMessagingService.SMSMessagingSession messagingSession) {
            return base.Channel.SaveMessagingSessionAsync(messagingSession);
        }
        
        public void ChangeSMSMessagingSessionStatus(uint id, byte newStatus) {
            base.Channel.ChangeSMSMessagingSessionStatus(id, newStatus);
        }
        
        public System.Threading.Tasks.Task ChangeSMSMessagingSessionStatusAsync(uint id, byte newStatus) {
            return base.Channel.ChangeSMSMessagingSessionStatusAsync(id, newStatus);
        }
        
        public System.Collections.Generic.List<ExternalBanking.SMSMessagingService.SMSMessagingSession> GetSMSMessagingSessions(ExternalBanking.SMSMessagingService.SearchSMSMessagingSession searchParams) {
            return base.Channel.GetSMSMessagingSessions(searchParams);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ExternalBanking.SMSMessagingService.SMSMessagingSession>> GetSMSMessagingSessionsAsync(ExternalBanking.SMSMessagingService.SearchSMSMessagingSession searchParams) {
            return base.Channel.GetSMSMessagingSessionsAsync(searchParams);
        }
        
        public void DeleteMessagingSession(uint id) {
            base.Channel.DeleteMessagingSession(id);
        }
        
        public System.Threading.Tasks.Task DeleteMessagingSessionAsync(uint id) {
            return base.Channel.DeleteMessagingSessionAsync(id);
        }
        
        public void SendMessage(string phoneNumber, ulong customerNumber, string message, int registrationSetNumber, int messageType, ushort source, string externalId) {
            base.Channel.SendMessage(phoneNumber, customerNumber, message, registrationSetNumber, messageType, source, externalId);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(string phoneNumber, ulong customerNumber, string message, int registrationSetNumber, int messageType, ushort source, string externalId) {
            return base.Channel.SendMessageAsync(phoneNumber, customerNumber, message, registrationSetNumber, messageType, source, externalId);
        }
        
        public void SendMessages(System.Collections.Generic.List<ExternalBanking.SMSMessagingService.SMSMessage> messages, string description) {
            base.Channel.SendMessages(messages, description);
        }
        
        public System.Threading.Tasks.Task SendMessagesAsync(System.Collections.Generic.List<ExternalBanking.SMSMessagingService.SMSMessage> messages, string description) {
            return base.Channel.SendMessagesAsync(messages, description);
        }
        
        public void SendOneMessage(ExternalBanking.SMSMessagingService.OneMessage message) {
            base.Channel.SendOneMessage(message);
        }
        
        public System.Threading.Tasks.Task SendOneMessageAsync(ExternalBanking.SMSMessagingService.OneMessage message) {
            return base.Channel.SendOneMessageAsync(message);
        }
    }
}
